# Generated by Django 4.0.3 on 2022-05-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='time',
            field=models.IntegerField(null=True),
        ),
    ]
