# Generated by Django 4.0.3 on 2022-05-25 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_examtype_end_examtype_start_result_exam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examtype',
            old_name='category',
            new_name='cat',
        ),
    ]
