# Generated by Django 4.0.3 on 2022-05-25 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_rename_category_examtype_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examtype',
            old_name='cat',
            new_name='cname',
        ),
    ]
